// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	ERRORS: {
		/**
		 * I​n​v​a​l​i​d​ ​u​s​e​r​ ​c​r​e​d​e​n​t​i​a​l​s​!
		 */
		INVALID_CREDENTIALS: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​!
		 */
		UNKNOWN: string
	}
	BRANDING: {
		/**
		 * S​v​e​l​t​e​k​i​t​ ​S​k​e​l​e​t​o​n​ ​S​a​a​S
		 */
		NAME: string
	}
	SEO: {
		/**
		 * S​v​e​l​t​e​k​i​t​ ​S​k​e​l​e​t​o​n​ ​S​a​a​S
		 */
		TITLE: string
		/**
		 * S​v​e​l​t​e​k​i​t​ ​S​k​e​l​e​t​o​n​ ​S​a​a​S​ ​t​e​m​p​l​a​t​e
		 */
		DESCRIPTION: string
	}
	ROUTE: {
		AUTH: {
			/**
			 * L​o​g​ ​I​n
			 */
			SIGN_IN: string
			/**
			 * S​i​g​n​ ​U​p
			 */
			SIGN_UP: string
			/**
			 * L​o​g​ ​O​u​t
			 */
			SIGN_OUT: string
			/**
			 * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t
			 */
			CREATE_ACCOUNT: string
			/**
			 * S​u​b​m​i​t
			 */
			SUBMIT: string
			/**
			 * E​m​a​i​l
			 */
			EMAIL: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			PASSWORD: string
			/**
			 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
			 */
			NO_ACCOUNT: string
		}
	}
	PAGES: {
		HOME: {
			/**
			 * W​e​b​s​i​t​e​ ​T​a​g​l​i​n​e​ ​i​n​ ​E​n​g​l​i​s​h
			 */
			TAG_LINE: string
		}
		PROFILE: {
			/**
			 * C​h​a​n​g​e​ ​P​a​s​s​w​o​r​d
			 */
			CHANGE_PASSWORD: string
		}
	}
}

export type TranslationFunctions = {
	ERRORS: {
		/**
		 * Invalid user credentials!
		 */
		INVALID_CREDENTIALS: () => LocalizedString
		/**
		 * Something went wrong!
		 */
		UNKNOWN: () => LocalizedString
	}
	BRANDING: {
		/**
		 * Sveltekit Skeleton SaaS
		 */
		NAME: () => LocalizedString
	}
	SEO: {
		/**
		 * Sveltekit Skeleton SaaS
		 */
		TITLE: () => LocalizedString
		/**
		 * Sveltekit Skeleton SaaS template
		 */
		DESCRIPTION: () => LocalizedString
	}
	ROUTE: {
		AUTH: {
			/**
			 * Log In
			 */
			SIGN_IN: () => LocalizedString
			/**
			 * Sign Up
			 */
			SIGN_UP: () => LocalizedString
			/**
			 * Log Out
			 */
			SIGN_OUT: () => LocalizedString
			/**
			 * Create an account
			 */
			CREATE_ACCOUNT: () => LocalizedString
			/**
			 * Submit
			 */
			SUBMIT: () => LocalizedString
			/**
			 * Email
			 */
			EMAIL: () => LocalizedString
			/**
			 * Password
			 */
			PASSWORD: () => LocalizedString
			/**
			 * Don't have an account?
			 */
			NO_ACCOUNT: () => LocalizedString
		}
	}
	PAGES: {
		HOME: {
			/**
			 * Website Tagline in English
			 */
			TAG_LINE: () => LocalizedString
		}
		PROFILE: {
			/**
			 * Change Password
			 */
			CHANGE_PASSWORD: () => LocalizedString
		}
	}
}

export type Formatters = {}
